wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    start_time: 1641296797
    t:
      3:
      - 2
      - 3
      - 16
      - 17
      4: 3.7.4
      5: 0.12.4
      8:
      - 5
distanceTolerance:
  desc: null
  value: 0.01
flags:
  desc: null
  value:
  - -momentum
isSymmetric:
  desc: null
  value: false
k:
  desc: null
  value: 7
learningRate:
  desc: null
  value: 0.5
numIterations:
  desc: null
  value: 35000
numStepsPerIteration:
  desc: null
  value: 200
tolerance:
  desc: null
  value: 10
variant:
  desc: null
  value: b
xDim:
  desc: null
  value:
  - 10000
  - 7
